front-end/package.json, front-end/yarn.lock
axios, redux-toolkit을 사용하기 위한 라이브러리를 설치했습니다.
feature/mainpage에서 모두 다 하려고 했었는데, 이전에 분리해서 했던 룰을 지키기 위해 다른 feature로 했습니다.
----
library 설치
=> Add : Axios, redux-toolkit 라이브러리 설치

front-end/components/Home/Card.tsx, front-end/components/Home/CardList.tsx, front-end/components/Home/ThumbnailList.tsx, front-end/components/Lectures/LectureCard.tsx, front-end/pages/index.tsx, front-end/shared/utils/getDiffDays.ts
메인페이지 데이터 불러오기 수정
----
1. 수정사항 index.tsx
- 새로운 강의를 반환하는 함수 추가 shared/utils/getDiffDays (강의  출시가 현재 날짜와 비교해서 30일 이하면 신규 강의)
- 기초강의를 구분하기 위해 난이도가 1이면 basicLecture로 추가되게 함.
- 강의 이어보기는 회원기능이 되어야 가능함.
=> Add features

front-end/components/modals/LoginForm.tsx, front-end/components/modals/LoginModal.tsx
=> Add Login Form

front-end/components/Lectures/LectureList.tsx, front-end/components/Lectures/SelectorList.tsx, front-end/pages/details.tsx, front-end/pages/index.tsx, front-end/pages/lectures.tsx, front-end/shared/constants/apis.ts, front-end/shared/constants/constant.ts
- API들을 어떻게 관리하는것이 좋을지 생각해보다가, 하나에 묶어서 관리하는건 어떨까 싶어서 따로 뽑아봤습니다.
----
- constants/apis에 관리하면, 나중에 api 변경에도 유연하게 대응할 수 있을것 같습니다.
- BASE_URL은 반드시 .env로 빼서 나중에 활용해야하고, api리스트 또한, gitignore에 추가해서 가려주는것이 맞다고 생각합니다.
- 참고로 우리학교 졸업작품 전시회도 Network 탭 보면 api에 모든게 다 보입니다..
- (예시) 
- Request URL: https://cs.skku.edu/gp/uploads/posts/1103/20211122013036_video_1_%EC%9D%B4%EC%A0%95%EC%9D%B8.mp4
- 권한 확인 없이 무언가 수정되거나 조회되면 안될것 같습니다..
=> 1. constants에 apis 추가.

front-end/components/Lectures/LectureList.tsx, front-end/components/Lectures/TopSearchbar.tsx, front-end/feature/lecture/lectureSlice.ts
강의 검색 기능을 추가했습니다 (API 사용 X) 
----
-  filter로 검색기능 구현
-  영어는 대소문자 관계없이 검색 가능, 강의명, 상세정보에 검색어가
포함되면 나오게 했음
- reducer에 임시로 하나 추가 setAllLectures
=> 강의검색 기능 추가(임시)

front-end/components/Lectures/ContentCard.tsx, front-end/components/Lectures/LectureCard.tsx, front-end/components/Lectures/LectureList.tsx, front-end/pages/lectures.tsx, front-end/shared/apis/index.ts, front-end/shared/apis/lectureApi.ts
- Lecture부분 api 추가 및 연동입니다.
----
- 강의 카테고리 불러오기
- 강의 전체 불러오기
- 강의 각 카테고리별 강의 불러오기 (백엔드에서 api 체크중)
- 검색기능
=> feat: api연동 및 카테고리 불러오기, 전체강의 검색 추가

front-end/components/Home/Card.tsx, front-end/components/Home/CardList.tsx, front-end/pages/index.tsx
- 최신강의, 강의 추천 항목 나오게 추가
----
-  api 수정한것 이용해서 최신강의, 강의추천 추가
- 강의 이어보기 기능
- 메인페이지에서 강의에 description 대신에 강사 이름으로 출력되게 바꿔야함 
- 백엔드에 요청 완료
=> feat: 메인페이지에서 최신강의, 강의 추천기능 추가

front-end/components/Lectures/LectureList.tsx, front-end/pages/index.tsx
- amplify build 안되는 오류
----
- ./components/Lectures/LectureList.tsx:22:4
Type error: Expected 1 arguments, but got 0.
- 해결위해서 임시로 인수넣음
=> chore: fetchLectureList에서 parameter 안줬더니 build가 안되는 오류 발생. 일단 임시로 ''로 처리

front-end/feature/lecture/lectureSlice.ts
build 에러 해결, build 해서 테스트 완료
----
- type[0].id 이런식으로 접근할 때, id가 undefined라고 빌드가 막힘. 임시로 type any로 변경
i
=> chore: type 안맞아서 build가 안되는 오류 해결. (reducer에 들어가는 타입 any로 변경)

front-end/package.json
pr에 자동으로 들어가는 메세지 입니다.
빌드 후 s3에 배포 위해서 스크립트 수정
----
- 자세한 내용은 프론트엔드 노션 참조 바랍니다.
- [Link](https://www.notion.so/S3-a3bb2f896e704d66bcfe9f3895eb2033)
=> chore(package.json): package.json에서 build시에 필요한 명령어 추가

front-end/components/Main/CardList.tsx, front-end/components/Main/Dashboard.tsx, front-end/components/Main/MainBanner.tsx, front-end/components/Main/Notice.tsx, front-end/next.config.js, front-end/pages/index.tsx, front-end/shared/apis/Main/bannerApi.ts
- api 연동 테스트
- CORS 문제로 내일 발표를 할 수 없어서, proxy 설정을 통해서 임시로 실행되게 해두었습니다. cors 수정이 끝나면 next.config 내용 제거 예정입니다.
----
-  프록시로 설정해두더라도, img tag 에서 src를 불러올 수 없었습니다. 실제 요청은 localhost이므로
- crossOrigin property를 통해서 cors를 허용해줄 수 있습니다. 
-  환경변수 설정은 [link](https://www.notion.so/rbals0445/env-ca0fbab5bd8d42aebe6c8434ab285398)참조 바랍니다
=> feat(api연동): api연동 테스트, cors문제 해결 필요

front-end/components/Lectures/CardItem.tsx, front-end/components/Lectures/ContentCard.tsx, front-end/components/Lectures/ContentMenu.tsx, front-end/components/Lectures/LectureCard.tsx, front-end/components/Lectures/LectureList.tsx, front-end/components/Lectures/TagCard.tsx, front-end/components/Lectures/TopSearchbar.tsx, front-end/package-lock.json, front-end/package.json, front-end/shared/apis/lectureApi.ts, front-end/yarn.lock
내용을 적어주세요
카드 아이템 하드코딩이 아닌 api를 통해 출력
----
- 내용을 적어주세요
=> feat(lecture-selection-page): 카드 리스트 하드 코딩이 아닌 api를 통해 출력

front-end/apis/index.ts
쿠키 사용을 위해 수정했습니다.
----
- axios 요청에 withCredentials: true로 변경
=> fix: axios 요청에 withCredentials: true로 변경

front-end/apis/index.ts, front-end/components/Courses/Details/CourseHeader.tsx, front-end/components/Main/MainBanner.tsx, front-end/next.config.js, front-end/pages/index.tsx
=> fix: proxy 설정

front-end/components/Header.tsx, front-end/components/modals/LoginForm.tsx, front-end/components/modals/LoginModal.tsx, front-end/components/modals/SignUpForm.tsx, front-end/pages/auth/callbackError.tsx, front-end/pages/auth/login/callback.tsx, front-end/pages/auth/signup/callback.tsx
로그인 기능 완성했습니다.
----
- 중복체크가 안되던 문제 해결
- 파일 및 변수명 때문에 에러 발생하던 것 해결
- 로그인 및 회원가입 시 이메일이 발송되지 않은 경우를 캐치하도록 변경
- 로그인 및 회원가입 테스트 완료
=> fix: 중복체크 수정 및 로그인 완성

front-end/components/Courses/Details/CourseHeader.tsx
=> thumbnail 이미지 위치 변경

front-end/components/Courses/Details/LectureListItem.tsx, front-end/components/Courses/Details/LectureListSection.tsx, front-end/components/Main/CardList.tsx, front-end/components/Main/LectureList.tsx, front-end/pages/index.tsx
=> chore: 시연 위해 디자인 수정

front-end/apis/Courses/courseApi.ts, front-end/apis/Lectures/lectureApi.ts, front-end/components/Courses/Details/LectureListItem.tsx, front-end/components/Courses/List/LectureCard.tsx, front-end/components/Lectures/LecturePicker.tsx, front-end/pages/lectures/[lectureId].tsx, front-end/pages/lectures/index.tsx, front-end/utils/durationToHhMmSs.ts
=> feat: 비디오플레이어 옆에 LecturePicker 추가

front-end/apis/Lectures/lectureApi.ts, front-end/pages/courses/index.tsx, front-end/pages/lectures/[lectureId].tsx
- 강의 기록 저장 추가. (현재 테스트 안됨), 비디오가 안불러와짐. 
----
- 내용을 적어주세요
=> feat: add lecture history

front-end/components/Main/LectureList.tsx, front-end/pages/index.tsx
- 메인페이지의 강의 클릭시에 상세페이지로 이동
----
- 이미지가 없는경우 default 이미지 설정.
- https://www.notion.so/rbals0445/30bfa6ed4dee4e79aefdf16b6a523669
=> fix : 메인페이지 강의 클릭시 상세페이지로 이동

front-end/components/Courses/List/TopSearchbar.tsx, front-end/components/MyPage/MyPageLayout.tsx, front-end/components/MyPage/bookmark.tsx, front-end/components/MyPage/completed.tsx, front-end/components/MyPage/history.tsx, front-end/components/MyPage/learning.tsx, front-end/components/MyPage/my-qna.tsx, front-end/components/common/BreadCrumb.tsx, front-end/pages/courses/index.tsx
=> feat: add breadcrumb

front-end/apis/MyPage/index.ts, front-end/components/Header.tsx, front-end/components/MyPage/SideMenu.tsx, front-end/components/MyPage/completed.tsx, front-end/components/MyPage/history.tsx, front-end/components/MyPage/learning.tsx, front-end/constants/MyPage/index.ts, front-end/next.config.js, front-end/pages/my-page/[category].tsx
- 대시보드에 넣을게 없어서 일단 제거했습니다.
- my-page로 이동시에 my-page/history로 redirect하게 수정했습니다.
----
- 내용을 적어주세요
=> feat : 마이페이지 대시보드 삭제, api 호출 분리

front-end/pages/my-page/[category].tsx
=> hotfix: 마이페이지에 컴포넌트명이 달라서 생기는 문제 해결

.github/workflows/main.yml
=> chore: script 수정

front-end/next.config.js
=> chore: 타입검사 disabled (임시)

front-end/pages/my-page/index.tsx
=> chore: mypage index에서 다른 페이지로 이동

front-end/components/MyPage/Bookmark.tsx, front-end/components/MyPage/Completed.tsx, front-end/components/MyPage/History.tsx, front-end/components/MyPage/Learning.tsx
컴포넌트의 대소문자만 변경시 git이 감지하지 못했음
`git config core.ignorecase false` 로 해결
----
- 내용을 적어주세요
=> chore: 컴포넌트 대소문자 구분

front-end/package.json
=> chore: ec2에서 빌드되게 수정

front-end/components/Main/MainBanner.tsx
내용을 적어주세요
----
- 서버의 환경변수 설정 문제로 메인페이지가 나오지 않음.
-  싱크 맞추기 위해서, 변수명 변경
=> chore: 환경변수 수정

front-end/components/Main/MainBanner.tsx
=> chore: 백엔드 api 주소에 맞게 URL 수정

front-end/components/Header.tsx, front-end/components/Lectures/LecturePicker.tsx, front-end/components/Main/MainBanner.tsx, front-end/types/Lecture/index.ts
- 메인배너 클릭시 강의 검색으로 이동
----
- 메인배너 클릭시 강의 검색으로 이동
- 강의보기 페이지에 있는 css 오류 수정
=> feat: 메인배너 클릭시 강의 검색으로 이동

front-end/components/Courses/List/DifficultyList.tsx, front-end/components/Header.tsx
내용을 적어주세요
----
- 헤더에서 엔터키로 검색 추가
- 난이도 검색창에서 spread operator 순서 변경
=> feat: 헤더에서 엔터키로 검색 추가

front-end/components/Courses/List/TopSearchbar.tsx
=> feat: 키워드 검색시에 검색바에 키워드 노출, 그렇지 않으면 검색바 비우기

.github/workflows/main.yml
=> chore: action 파일 수정

.github/workflows/main.yml
=> chore: git action 수정

front-end/apis/MyPage/index.ts, front-end/components/MyPage/Completed.tsx, front-end/components/MyPage/History.tsx, front-end/components/MyPage/Learning.tsx, front-end/pages/questions/course/[courseId].tsx, front-end/types/MyPage/index.ts
- 빌드 오류로 서버가 죽어서 임시로 push 합니다
----
- mypage 내가 신청한강좌보기 기능 추가 (임시)
=> feat : mypage 내가 신청한강좌보기 기능 추가 (임시)

.github/workflows/check-build.yml, .github/workflows/check_build.yml, front-end/next.config.js, front-end/pages/questions/course/[courseId].tsx
배포전 빌드 테스트를 위한 yml 파일 추가
----
- 내용을 적어주세요
=> chore: build test

front-end/components/Courses/Details/CourseHeader.tsx, front-end/components/MyPage/Learning.tsx
- 강좌신청 버튼을 만들었습니다.
- 로그인유저
- 강의 신청여부에 따라 버튼이 다르게 나타남
- 비로그인 유저
- 강좌 신청 버튼 클릭시에 로그인창 노출
----
- 내용을 적어주세요
- Modal 깔끔하게 사용할 수 있게 구조 변경
- 401이나 403 404같은 에러일때 올바른 에러페이지로 redirect 해주는 코드 추가
=> feat: 강좌 신청버튼 생성

front-end/components/modals/LoginForm.tsx, front-end/pages/courses/index.tsx
[fix(로그인폼): 가입되지 않은 이메일도 메일 발송하던 문제 fix]
----
- 내용을 적어주세요
=> fix(로그인폼): 가입되지 않은 이메일도 메일 발송하던 문제 fix

front-end/components/Header.tsx
Header css 변경
----
- 내용을 적어주세요
=> chore: header 변경

front-end/apis/QnA/qnaApi.ts, front-end/components/Header.tsx, front-end/components/Questions/AnswerForm.tsx, front-end/components/Questions/QuestionBox.tsx, front-end/components/Questions/QuestionForm.tsx, front-end/components/Questions/QuestionTable.tsx, front-end/hooks/useCourseDetailInfo.ts, front-end/hooks/useModal.tsx, front-end/pages/questions/[questionId]/index.tsx, front-end/pages/questions/course/[courseId].tsx
내용을 적어주세요
----
- type 추가
- 코드 리팩토링
- 권한 없는 유저들은 질문 할 수 없게 수정
- 답변을 일반유저가 달 수 없어야 하는데, 권한을 서버에서 체크하는것이 나을것 같음. 클라에서 체크 시 예외가 너무 많음.
- 불필요한 api 호출들이 필요. 403때 alert 보여주는것이 나음.
=> feat: QnA 기능 정상동작하도록 수정

front-end/apis/Courses/courseApi.ts, front-end/apis/QnA/qnaApi.ts, front-end/components/Courses/Details/QnA.tsx, front-end/components/Questions/AnswerForm.tsx, front-end/components/Questions/QuestionTable.tsx, front-end/hooks/useCourseDetailInfo.ts, front-end/pages/questions/course/[courseId].tsx
내용을 적어주세요
----
- 필요한 API 호출해서, 값 가공해서 사용
- 권한없는 유저가 답변 달시에 로그인 유도
=> feat: api 중복호출 제거, 권한 확인해서 답변 달게 수정

front-end/components/Courses/Details/QnA.tsx, front-end/components/Courses/Details/QnAItem.tsx
내용을 적어주세요
----
- 질문 제목이 올바르게 올라오도록 수정
=> chore: qna에서 질문이 노출되게 수정

front-end/components/Header.tsx
=> chore: header 권한 확인후에 로그인 버튼이 깜빡거리며 로그아웃 버튼으로 렌더되는 문제 해결

front-end/apis/Lectures/lectureApi.ts, front-end/apis/MyPage/index.ts, front-end/components/Main/RecentLecture.tsx, front-end/components/MyPage/Completed.tsx, front-end/components/MyPage/History.tsx, front-end/components/MyPage/Learning.tsx, front-end/components/MyPage/MyQna.tsx, front-end/pages/index.tsx, front-end/pages/lectures/[lectureId].tsx, front-end/types/MyPage/index.ts
=> feat: 수강 중인 강좌, 수강 완료 강좌 기능 추가

front-end/components/MyPage/Learning.tsx
=> chore: console 제거 및 강의가 0일때 로직 수정

front-end/apis/MyPage/index.ts, front-end/components/MyPage/MyQna.tsx, front-end/components/Questions/QuestionBox.tsx, front-end/types/Course/index.ts, front-end/types/MyPage/index.ts, front-end/utils/getTimeBefore.ts
- 내 질문 답변 기능 추가
----
- 내용을 적어주세요
=> feat: 내 질문 답변 기능 추가

front-end/apis/Main/index.ts, front-end/apis/MyPage/index.ts, front-end/components/Main/CourseList.tsx, front-end/components/Main/RecentLecture.tsx, front-end/hooks/useAxios.ts, front-end/pages/index.tsx, front-end/types/Main/index.ts
- any script -> typescript 적용
- api call 커스텀훅으로 교체.
----
- 내용을 적어주세요
- 로딩컴포넌트도 필요하고, 불편함을 좀 느낀후에 React query로 변경 예정
=> 메인페이지 소스코드 리팩토링 (api call 커스텀 훅 생성)

front-end/components/Courses/List/DifficultyList.tsx, front-end/components/Courses/List/TopSearchbar.tsx
=> chore: refactor code

.github/workflows/main.yml
=> chore: yaml파일 수정. ci시에 merge conflict 문제 해결 용도

.github/workflows/main.yml
=> chore: ci시에 merge conflict 해결

front-end/apis/Courses/courseApi.ts, front-end/apis/QnA/qnaApi.ts, front-end/components/Courses/Details/CourseHeader.tsx, front-end/components/Courses/Details/LectureList.tsx, front-end/components/Header.tsx, front-end/components/Questions/AnswerForm.tsx, front-end/hooks/useCourseDetailInfo.ts, front-end/hooks/useModal.tsx, front-end/pages/courses/[courseId].tsx, front-end/query/hooks/CourseDetail/index.ts, front-end/query/hooks/CourseDetail/queryKeys.ts
- 강의 상세 페이지 react-query hook으로 전환
- useModal에서 setState를 넘겨주는것보다 setState를 해주는 이벤트핸들러 전달.
----
- 내용을 적어주세요
=> feat: 강의상세 페이지 react-query로 전환, useModal에서 setState넘기는것 제거

front-end/apis/Lectures/lectureApi.ts, front-end/components/Lectures/LecturePicker.tsx, front-end/pages/lectures/[lectureId].tsx, front-end/query/hooks/CourseDetail/index.ts, front-end/query/hooks/Lecture/index.ts, front-end/query/hooks/Lecture/queryKeys.ts
- 강의재생 페이지 react-query hook 적용
----
- 내용을 적어주세요
=> feat: 강의재생 페이지 react-query 적용

front-end/apis/MyPage/index.ts, front-end/components/Main/RecentLecture.tsx, front-end/components/MyPage/Completed.tsx, front-end/components/MyPage/History.tsx, front-end/components/MyPage/Learning.tsx, front-end/pages/_app.tsx, front-end/pages/my-page/[category].tsx, front-end/query/hooks/MyPage/index.ts, front-end/query/hooks/MyPage/queryKeys.ts
- react-query hook으로 변경
- 코드 리팩토링
----
- 내용을 적어주세요
=> feat: 최근시청강의, 수강중인 강좌 react-query hook 적용

front-end/components/Header.tsx, front-end/components/modals/LoginForm.tsx, front-end/components/modals/LoginModal.tsx, front-end/components/modals/SignUpForm.tsx, front-end/components/modals/SignUpModal.tsx, front-end/styles/output.css
=> 로그인/회원가입 Modal TailwindCSS 수정

front-end/pages/index.tsx
CourseList margin Issue Resolved
=> CourseList margin Issue Resolved
